name: Executar testes Cypress

on:
  push:
    branches:
      - main  # Aciona o workflow em caso de push na branch main do repositório de testes
  repository_dispatch:
    types: [run-cypress-tests]  # Esse evento é disparado pelo repositório da aplicação

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código dos testes
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Rodar Cypress contra o ambiente local
        run: npm cypress run --reporter mochawesome --reporter-options reportDir=cypress/screenshots,overwrite=false,html=true,json=false"

      - name: Upload do relatório de testes
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-report
          path: cypress/screenshots/
