name: Executar testes Cypress

on:
  push:
    branches:
      - main  # Aciona o workflow em caso de push na branch main do repositório de testes
  repository_dispatch:
    types: [run-cypress-tests]  # Esse evento é disparado pelo repositório da aplicação

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código dos testes
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Rodar Cypress com Mochawesome e Cypress Cloud
        run: npx cypress run --record --key ${{ secrets.CYPRESS_CLOUD_KEY }} --reporter mochawesome --reporter-options reportDir=cypress/results,overwrite=false,html=true,json=true

      - name: Upload do relatório Mochawesome
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-mochawesome-report
          path: cypress/results/

      - name: Upload dos vídeos dos testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/
