name: Executar testes Cypress

on:
  push:
    branches:
      - main  # Aciona o workflow em caso de push na branch main do repositório de testes
  repository_dispatch:
    types: [run-cypress-tests]  # Esse evento é disparado pelo repositório da aplicação

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código dos testes
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Rodar Cypress com Mochawesome e Cypress Cloud
        run: npx cypress run --record --key ${{ secrets.CYPRESS_CLOUD_KEY }} --reporter mochawesome --reporter-options reportDir=cypress/results,overwrite=false,html=true,json=true

      - name: Gerar relatório consolidado
        run: |
          npx mochawesome-merge cypress/results/*.json > cypress/results/report.json
          npx marge cypress/results/report.json -o cypress/results/

      - name: Upload do relatório Mochawesome
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-mochawesome-report
          path: cypress/results/

      - name: Upload dos vídeos dos testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/

      - name: Salvar link do Cypress Cloud
        run: |
          echo "Obtendo link do Cypress Cloud..."
          CYPRESS_URL=$(npx cypress run --record --key ${{ secrets.CYPRESS_CLOUD_KEY }} --reporter mochawesome --reporter-options html=true,json=true 2>&1 | tee output.log | grep -o 'https://cloud.cypress.io/projects/[^ ]*')
          echo "$CYPRESS_URL" > cypress/results/cypress-cloud-url.txt
          echo "Recorded Run URL: $CYPRESS_URL"

      - name: Upload do link do Cypress Cloud
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-cloud-url
          path: cypress/results/cypress-cloud-url.txt
