name: Executar testes Cypress

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [run-cypress-tests]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código dos testes
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Rodar Cypress com Mochawesome e Cypress Cloud
        run: |
          set -o pipefail
          npx cypress run --record --key ${{ secrets.CYPRESS_CLOUD_KEY }} --reporter mochawesome --reporter-options reportDir=cypress/results,overwrite=false,html=true,json=true | tee cypress-output.log

      - name: Capturar e salvar link do Cypress Cloud
        run: |
          mkdir -p cypress/results
          CLOUD_URL=$(grep -oE 'https://cloud\.cypress\.io/projects/[^ ]+' cypress-output.log | head -n 1)
          
          if [[ -z "$CLOUD_URL" ]]; then
            echo "ERRO: Link do Cypress Cloud não encontrado!"
            exit 1
          fi

          echo "$CLOUD_URL" > cypress/results/cypress-cloud-url.txt
          echo "Link salvo: $CLOUD_URL"

      - name: Upload do relatório Mochawesome
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-mochawesome-report
          path: cypress/results/

      - name: Upload dos vídeos dos testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/

      - name: Upload do link do Cypress Cloud
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-cloud-url
          path: cypress/results/cypress-cloud-url.txt
